package SocialGraph;

import ArrayList.ArrayUnorderedList;
import User.*;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *  Janela para o ShortPath
 */
public class fastFriendsSkills extends javax.swing.JInternalFrame {

    
    private SocialGraph social;
    private ArrayUnorderedList<String> skills;
    /**
     * Creates new form ShortPath
     * @param social grafo
     */
    public fastFriendsSkills(SocialGraph social) {
        initComponents();
        this.social=social;
        this.skills=new ArrayUnorderedList<>();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldFirst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddSkill = new javax.swing.JButton();
        jTextFieldSkill = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Fast Friends Skills");

        jLabel1.setText("Procure se consegue contactar utilizadores com os skills que inserir, , via 1 unico intermediario.");

        jLabel2.setText("-->");

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("User Mail:");

        jLabel5.setText("Skills");

        AddSkill.setText("Add Skill");
        AddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSkillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldSkill)))
                    .addComponent(jLabel1))
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFirst)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddSkill)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mail=jTextFieldFirst.getText();
            
            String s="";
            if(social.fastFriendsSkills(mail, skills).size()==0){
                JOptionPane.showMessageDialog(this, "Nao consegue conectar-se a ninguem que com estes skills");
                
            }else{
            Iterator<User> it=social.fastFriendsSkills(mail, skills).iterator();
            while(it.hasNext()){
                s+=it.next().toString()+"\n";
            }
             textArea1.setText(s);
            }
           
        } catch (ElementNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            dispose();
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSkillActionPerformed
        String s=jTextFieldSkill.getText();
        skills.addToRear(s);
    }//GEN-LAST:event_AddSkillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSkill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldFirst;
    private javax.swing.JTextField jTextFieldSkill;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
